// Shared enum-like domain values. Keep database/API string values defined in one place.
const USER_ROLE = Object.freeze({
  ADMIN: 'admin',
  USER: 'user'
});

const RECORD_STATUS = Object.freeze({
  ACTIVE: 'active',
  INACTIVE: 'inactive'
});

const PRODUCT_STATUS = Object.freeze({
  ACTIVE: RECORD_STATUS.ACTIVE,
  INACTIVE: RECORD_STATUS.INACTIVE
});

const PAYMENT_METHOD = Object.freeze({
  COD: 'cod',
  BANK_TRANSFER: 'bank_transfer'
});

const PAYMENT_STATUS = Object.freeze({
  PENDING_PAYMENT: 'pending_payment',
  UNDER_REVIEW: 'payment_under_review',
  PAID: 'paid',
  EXPIRED: 'payment_expired',
  CANCELLED: 'payment_cancelled',
  REFUND_PENDING: 'refund_pending',
  PARTIALLY_REFUNDED: 'partially_refunded',
  REFUNDED: 'refunded'
});

const ORDER_STATUS = Object.freeze({
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  PROCESSING: 'processing',
  SHIPPING: 'shipping',
  DELIVERY_FAILED: 'delivery_failed',
  DELIVERED: 'delivered',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled'
});

const MAX_DELIVERY_RETRIES = 1;

const RETURN_REASON = Object.freeze({
  WRONG_SIZE: 'wrong_size',
  NOT_AS_EXPECTED: 'not_as_expected',
  CHANGED_MIND: 'changed_mind',
  DEFECTIVE: 'defective',
  OTHER: 'other'
});

const RETURN_STATUS = Object.freeze({
  REQUESTED: 'requested',
  APPROVED: 'approved',
  AWAITING_RETURN: 'awaiting_return',
  REJECTED: 'rejected',
  RECEIVED: 'received',
  INSPECTING: 'inspecting',
  INSPECTION_APPROVED: 'inspection_approved',
  INSPECTION_REJECTED: 'inspection_rejected',
  REFUND_PENDING: 'refund_pending',
  COMPLETED: 'completed'
});

const REFUND_STATUS = Object.freeze({
  PENDING: 'pending',
  PROCESSING: 'processing',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCELLED: 'cancelled'
});

const PAYMENT_METHOD_ALIASES = Object.freeze({
  cod: PAYMENT_METHOD.COD,
  cash: PAYMENT_METHOD.COD,
  bank: PAYMENT_METHOD.BANK_TRANSFER,
  bank_transfer: PAYMENT_METHOD.BANK_TRANSFER,
  qr: PAYMENT_METHOD.BANK_TRANSFER,
  card: PAYMENT_METHOD.BANK_TRANSFER
});

const createValueSet = enumObject => new Set(Object.values(enumObject));

const USER_ROLES = createValueSet(USER_ROLE);
const RECORD_STATUSES = createValueSet(RECORD_STATUS);
const PAYMENT_METHODS = createValueSet(PAYMENT_METHOD);
const PAYMENT_STATUSES = createValueSet(PAYMENT_STATUS);
const ORDER_STATUSES = createValueSet(ORDER_STATUS);
const RETURN_REASONS = createValueSet(RETURN_REASON);
const RETURN_STATUSES = createValueSet(RETURN_STATUS);
const REFUND_STATUSES = createValueSet(REFUND_STATUS);

const ORDER_STATUS_TRANSITIONS = Object.freeze({
  [ORDER_STATUS.PENDING]: new Set([
    ORDER_STATUS.PENDING,
    ORDER_STATUS.CONFIRMED,
    ORDER_STATUS.PROCESSING,
    ORDER_STATUS.CANCELLED
  ]),
  [ORDER_STATUS.CONFIRMED]: new Set([
    ORDER_STATUS.CONFIRMED,
    ORDER_STATUS.PROCESSING,
    ORDER_STATUS.CANCELLED
  ]),
  [ORDER_STATUS.PROCESSING]: new Set([
    ORDER_STATUS.PROCESSING,
    ORDER_STATUS.SHIPPING,
    ORDER_STATUS.CANCELLED
  ]),
  [ORDER_STATUS.SHIPPING]: new Set([
    ORDER_STATUS.SHIPPING,
    ORDER_STATUS.DELIVERY_FAILED,
    ORDER_STATUS.DELIVERED
  ]),
  [ORDER_STATUS.DELIVERY_FAILED]: new Set([
    ORDER_STATUS.DELIVERY_FAILED,
    ORDER_STATUS.SHIPPING,
    ORDER_STATUS.CANCELLED
  ]),
  [ORDER_STATUS.DELIVERED]: new Set([
    ORDER_STATUS.DELIVERED,
    ORDER_STATUS.COMPLETED
  ]),
  [ORDER_STATUS.COMPLETED]: new Set([ORDER_STATUS.COMPLETED]),
  [ORDER_STATUS.CANCELLED]: new Set([ORDER_STATUS.CANCELLED])
});

const RETURN_STATUS_TRANSITIONS = Object.freeze({
  [RETURN_STATUS.REQUESTED]: new Set([
    RETURN_STATUS.APPROVED,
    RETURN_STATUS.AWAITING_RETURN,
    RETURN_STATUS.REJECTED
  ]),
  [RETURN_STATUS.APPROVED]: new Set([
    RETURN_STATUS.AWAITING_RETURN,
    RETURN_STATUS.REJECTED
  ]),
  [RETURN_STATUS.AWAITING_RETURN]: new Set([RETURN_STATUS.RECEIVED]),
  [RETURN_STATUS.RECEIVED]: new Set([RETURN_STATUS.INSPECTING]),
  [RETURN_STATUS.INSPECTING]: new Set([
    RETURN_STATUS.INSPECTION_APPROVED,
    RETURN_STATUS.INSPECTION_REJECTED
  ]),
  [RETURN_STATUS.INSPECTION_APPROVED]: new Set([RETURN_STATUS.REFUND_PENDING]),
  [RETURN_STATUS.REFUND_PENDING]: new Set([RETURN_STATUS.COMPLETED]),
  [RETURN_STATUS.REJECTED]: new Set(),
  [RETURN_STATUS.INSPECTION_REJECTED]: new Set(),
  [RETURN_STATUS.COMPLETED]: new Set()
});

const REFUND_STATUS_TRANSITIONS = Object.freeze({
  [REFUND_STATUS.PENDING]: new Set([
    REFUND_STATUS.PROCESSING,
    REFUND_STATUS.FAILED,
    REFUND_STATUS.CANCELLED
  ]),
  [REFUND_STATUS.PROCESSING]: new Set([
    REFUND_STATUS.COMPLETED,
    REFUND_STATUS.FAILED
  ]),
  [REFUND_STATUS.FAILED]: new Set([
    REFUND_STATUS.PROCESSING,
    REFUND_STATUS.CANCELLED
  ]),
  [REFUND_STATUS.COMPLETED]: new Set(),
  [REFUND_STATUS.CANCELLED]: new Set()
});

const INVENTORY_HOLD_ORDER_STATUSES = new Set([
  ORDER_STATUS.CONFIRMED,
  ORDER_STATUS.PROCESSING,
  ORDER_STATUS.SHIPPING,
  ORDER_STATUS.DELIVERY_FAILED,
  ORDER_STATUS.DELIVERED
]);

const CANCELLABLE_ORDER_STATUSES = new Set([
  ORDER_STATUS.PENDING,
  ORDER_STATUS.CONFIRMED,
  ORDER_STATUS.PROCESSING
]);

const BANK_TRANSFER_FILTER_PAYMENT_STATUSES = new Set([
  '',
  PAYMENT_STATUS.PENDING_PAYMENT,
  PAYMENT_STATUS.UNDER_REVIEW,
  PAYMENT_STATUS.EXPIRED
]);

const ACTIVE_RETURN_STATUSES = Object.freeze([
  RETURN_STATUS.REQUESTED,
  RETURN_STATUS.APPROVED,
  RETURN_STATUS.AWAITING_RETURN,
  RETURN_STATUS.RECEIVED,
  RETURN_STATUS.INSPECTING,
  RETURN_STATUS.INSPECTION_APPROVED,
  RETURN_STATUS.REFUND_PENDING,
  RETURN_STATUS.COMPLETED
]);

const REVIEW_PAYMENT_STATUSES = new Set([
  PAYMENT_STATUS.UNDER_REVIEW
]);

module.exports = {
  ACTIVE_RETURN_STATUSES,
  BANK_TRANSFER_FILTER_PAYMENT_STATUSES,
  CANCELLABLE_ORDER_STATUSES,
  INVENTORY_HOLD_ORDER_STATUSES,
  MAX_DELIVERY_RETRIES,
  ORDER_STATUS,
  ORDER_STATUSES,
  ORDER_STATUS_TRANSITIONS,
  PAYMENT_METHOD,
  PAYMENT_METHODS,
  PAYMENT_METHOD_ALIASES,
  PAYMENT_STATUS,
  PAYMENT_STATUSES,
  PRODUCT_STATUS,
  RECORD_STATUS,
  RECORD_STATUSES,
  REFUND_STATUS,
  REFUND_STATUSES,
  REFUND_STATUS_TRANSITIONS,
  RETURN_REASON,
  RETURN_REASONS,
  RETURN_STATUS,
  RETURN_STATUSES,
  RETURN_STATUS_TRANSITIONS,
  REVIEW_PAYMENT_STATUSES,
  USER_ROLE,
  USER_ROLES
};
